### ISSUE TITLE
Test & my proporsal

### ISSUE THREAD

**Issue by akatsuki-love** [renesas-rz/rza2m-food-recognition-demo#2]
@TakaakiSuezawa 
Test. 
I want to do QA this corner to customer and sales person. How about do you think?

**Comment by Abid-ops** [comment]
Hello,
Thank you for your well-presented demo, I would like to point out some anomalies: 
After downloading the zip "rza2m-food-recognition-demo", I had several damaged files in the directory "rza2m-food-recognition-demo/e-AI_next_step_package/e-AI_next_step_package_data/GR-MANGO_food_menu_recognition/" (the errors indicated are "long path" --> to avoid them I copied the zip content directly into a local directory) 
Following your tutorial step-by-step, I got a black screen after flashing the GR-MANGO! 
From what I understand, you did not use e-AI translator to convert the image classification neural network "you used cygwin".
I have two questions:
Q1: How can I solve the black screen problem?  
Q2: I already have a neural network that I created with tensorflowLite and converted it to “.C” with Cygwin could you tell me how I can integrate this file into a new project from scratch in e2 studio (without copying the files from your demo).  
Thank you.
Abid

**Comment by akatsuki-love** [comment]
Thank you for trying our demonstration!
I am sorry, sevral files is damaged.
We have plan of creating release package to solve your problem.
Please wait fo a while.

Q1. Problem of black screen
A1.
    I have a question about this issue. Which guide did you get a black screen when you 　performed it beginner's guide or customization guide?
I want to know whether the intent of the problem is a hard factor or a soft factor.
If you are doing a beginner's guide, it's likely the cause of your monitor or other peripherals.

Q2. How to use your c source file(weight data)
A2.
       If you see chapter 6.1 of customerzation guide, you can change your file.
       As a reminder, this demonstration is a SW package that uses an AI model created as 　
       TFLM (Tensorflowlite micro), so you can use the c source code created with the current 
       e-AI translator. can not be used.

Akiko Yamanaka
Renesas Electronics

**Comment by Abid-ops** [comment]
Hello Akiko,
Thank you for your response, 
For Q1, I used both guides and I had the same problem I think we have a problem with the camera since I use a PI-CAMERA v1.3 and your colleague recommended me to use a PI-CAMERA 2.1. 

Have a nice day 
Abid

**Comment by akatsuki-love** [comment]
@Abid-ops
Thank you for telling me your detail.
If the camera is not the cause, please let us know again.

Best regards,
Akiko

**Comment by TakaakiSuezawa** [comment]
@Abid-ops 
I'm sorry for bothering you. This demo software supports only PI-CAMERA V2.1(IMX219). Please let us know if you have any trouble when you use PI-CAMERA V2.1.

Best Regards,
Takaaki Suezawa

**Comment by Abid-ops** [comment]
Hello Akiko, Takaaki,

I confirm that the demo works well with the PI-CAMERA V2.1, thank you for your answers.
For information: your colleague Sebastien WALGER from Renesas France assists me. I will get back to you if needed. 

Yours sincerely.
Abid

**Comment by TakaakiSuezawa** [comment]
@Abid-ops 
Thank you for informing your situation, we are relieved to hear to that.
And thank you for your support, Walger-san.

**Comment by akatsuki-love** [comment]
@Abid-ops 
Thank you for your good report! I contacted Sebastien WALGER immediatery.
If you need help how to implement your project, please contact directly by e-mail. Sebstien knows my e-mail address.
(Because here is open community space.)

Best regards,
Akiko

**Comment by Abid-ops** [comment]
Thank you Akiko for your support, we will exchange by mail from now on
Best regards 
Abid

**Comment by akatsuki-love** [comment]
This issue is solved.  I close this issue.
